### ISSUE TITLE
Umbrella Issue for examples in Hands-on lab and ecosystem integration

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#1403]
Now we have released the KubeVela 1.0.0, the next most important thing is to give more and more examples of how to use it.

We could add more examples into the into the [hands-on labs](https://kubevela.io/docs/platform-engineers/keda) sections and create more sections such as `Ecosystem Integration`, `Examples`, `Demos`, etc...

We have two aspects of examples could add.

## The existing examples

We already have [many existing examples](https://github.com/oam-dev/kubevela/tree/master/docs/examples) while they can't be found in our website. I think we could refine and explain more about these documentation in the `examples` folder and add them into the website.
The most valuable examples are:

- [x] Deployment rollout: https://github.com/oam-dev/kubevela/tree/master/docs/examples/deployment-rollout.
- [x] General Application workflow with patch trait: https://github.com/oam-dev/kubevela/tree/master/docs/examples/application
- [x] Define component custom status and use in Application: https://github.com/oam-dev/kubevela/tree/master/docs/examples/app-with-status
- [x] Add PVC into Definition： https://github.com/oam-dev/kubevela/issues/1291
- [x] Application Rollout and Revert: https://github.com/oam-dev/kubevela/issues/37
- [ ] `Code as observibility` story: promethus trait, grafana. https://github.com/oam-dev/catalog/tree/master/traits/metricstrait
- [x] API Gateway and route: Nginx/Kong... route trait  https://github.com/oam-dev/catalog/tree/master/traits/routetrait

## Integrate more with the cloud native ecosystem

- [x] Integrate istio with AppDeploy/AppRollout: https://github.com/oam-dev/kubevela/issues/1122 https://github.com/oam-dev/kubevela/issues/638 https://github.com/oam-dev/kubevela/issues/172
- [x] Integrate with dapr https://github.com/oam-dev/kubevela/issues/609
- [x] CI/CD story, Integrate with argocd/tekton/jenkins: https://github.com/oam-dev/kubevela/tree/master/docs/examples/argo https://github.com/oam-dev/kubevela/issues/453 https://github.com/oam-dev/kubevela/issues/36 .
- [x] Integrate with terraform and consume cloud resources https://github.com/oam-dev/kubevela/issues/698 
- [ ] security story: OPA https://www.openpolicyagent.org/
- [ ] integrate with middle ware resources and binding, database,storage,.. https://github.com/oam-dev/kubevela/issues/1358

**Comment by resouer** [comment]
Please split these samples into two categories:

### P0: `End User Guide`

This section is only about using `Application` `AppRollout` and `AppDeployment`, no definitions should be declared in this section (and all needed definitions should be pre-installed in KubeVela). This is P0 and we will list this category at top of sidebar.

```
Introduction
End User Guide
  - Define Application
  - Rollout Application
  ...
Platform Builder Guide
  ...
  - Hands-on Lab
Developer Experience Guide
  - Appfile
  - CLI
  - Dashboard
CLI References
Capability References
Roadmap
FAQ
```

> The end user guide is actually very easy to write: just post YAML sample and kubectl outputs, don't write too much words. The key here is decide what should be included in this section (i.e. what features your platform wants to provide by default).

### P1: More samples in `Platform Builder - Hands-on Lab`

This section is relatively less important, the existing `How-to` guide is useful enough.

**Comment by resouer** [comment]
The existing doc looks confusing, please consider below format:

```
# Sidebar

- Overview
  - Introduction
- Getting Started
  - Installation # move install vela kubectl cli here
  - Quick Start
- How it Works
  - Overview # concepts.md
  - Resource Model
  - Programmable Building Blocks
- Component Provider Guide
  - Overview # explain what is component and why, can leave to following PR
  - CUE
  - Helm
  - Raw Template
  - Cloud Services
- App Operator Guide
  - Deploy App
  - Manage App
  - Manual Scale
  - Attach Volume
  - Attach Sidecar
  - Append Label/Annotation
  - Provision Cloud Services
    - Alibaba RDS
    - Want More?
  - Monitoring
  - Progressive Rollout
  - Multi-Cluster Deployment
  - Want More?
- Platform Operator Guide
  - Defining Traits
  - Generating UI Forms
  - Hands-on Lab
 ```

**Comment by wonderflow** [comment]
@resouer Yes, planning to do a second round refactor for our doc site

**Comment by resouer** [comment]
@wonderflow I've sent a PR #1601 to fix the doc. Please add further docs following the new structure.

**Comment by resouer** [comment]
Please note do NOT mix tutorials with docs. Right now what we need are docs, e.g. `/docs/end-user/components/*` in PR #1601 , the are very simple, only spec + sample is enough, no need to tell stories with long sentences. The tutorials should be more end to end can be placed in separate dir.
